-- AlterTable
ALTER TABLE "patients" ADD COLUMN     "aceInhibitorLastDose" TIMESTAMP(3),
ADD COLUMN     "aceInhibitorName" TEXT,
ADD COLUMN     "anticoagulantLastDose" TIMESTAMP(3),
ADD COLUMN     "anticoagulantName" TEXT,
ADD COLUMN     "antiplateletLastDose" TIMESTAMP(3),
ADD COLUMN     "antiplateletName" TEXT,
ADD COLUMN     "arbLastDose" TIMESTAMP(3),
ADD COLUMN     "arbName" TEXT,
ADD COLUMN     "asaScore" INTEGER,
ADD COLUMN     "assessedBy" TEXT,
ADD COLUMN     "assessmentDate" TIMESTAMP(3),
ADD COLUMN     "assessmentNotes" TEXT,
ADD COLUMN     "bleedingRiskScore" INTEGER,
ADD COLUMN     "cardiovascularStatus" TEXT,
ADD COLUMN     "comorbidities" TEXT,
ADD COLUMN     "dDimerResult" TEXT,
ADD COLUMN     "dDimerTestDone" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dDimerValue" DOUBLE PRECISION,
ADD COLUMN     "dvtRiskScore" INTEGER,
ADD COLUMN     "finalRiskScore" INTEGER,
ADD COLUMN     "fitnessForSurgery" TEXT,
ADD COLUMN     "hasActiveCancer" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasBleedingDisorder" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasDVTHistory" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasLiverDisease" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasMobilityIssues" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasPressureSores" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasPriorDVT" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasRenalImpairment" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "metabolicStatus" TEXT,
ADD COLUMN     "mobilityStatus" TEXT,
ADD COLUMN     "nutritionalStatus" TEXT,
ADD COLUMN     "onACEInhibitors" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "onARBs" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "onAnticoagulants" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "onAntiplatelets" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "otherMedications" TEXT,
ADD COLUMN     "pressureSoreRisk" TEXT,
ADD COLUMN     "recentBleeding" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "respiratoryStatus" TEXT,
ADD COLUMN     "whoRiskClass" TEXT;
