/*
  Warnings:

  - You are about to drop the column `procedureConfirmed` on the `who_checklists` table. All the data in the column will be lost.
  - You are about to drop the column `recoveryPlan` on the `who_checklists` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "holding_area_assessments" ADD COLUMN     "allNotesDrugsChartsAttached" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "assistiveDeviceType" TEXT,
ADD COLUMN     "bloodPressure" TEXT,
ADD COLUMN     "canSupportRespiration" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "capOrCrownRemoved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "comorbidConditionsList" TEXT,
ADD COLUMN     "compareWithFolderName" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "compareWithOperationList" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "compareWithWardSlip" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "consentFormComplete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "consentNotSigned" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "consentRemarks" TEXT,
ADD COLUMN     "consentWitnessed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "crossCheckWithWristBand" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dateOfPreVisit" TIMESTAMP(3),
ADD COLUMN     "dentureNailPlatesRemoved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "gcs" INTEGER,
ADD COLUMN     "glassesContactLensRemoved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "headToToeAssessmentSatisfactory" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "height" DECIMAL(5,2),
ADD COLUMN     "investigationResultsAttached" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "jewelriesRemoved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "labInvestigationsCarriedOut" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "labResultsAbnormality" TEXT,
ADD COLUMN     "labResultsAvailable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "makeUpNailPolishRemoved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "maritalStatus" TEXT,
ADD COLUMN     "medsToDiscontinue" TEXT,
ADD COLUMN     "needToDiscontinueMeds" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "nilPerOralMaintained" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "onMedicationForComorbid" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "operationFeeNotYetPaid" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "operationFeePaid" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "operationSiteMarked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "operationSiteShaved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "pantiesOrBoxersRemoved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "patientDressedInGown" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "patientNotForReview" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "patientNotYetReviewed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "patientOnMedication" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "patientReadyForSurgery" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "patientReviewed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "patientStatedName" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "perioperativeNurse1" TEXT,
ADD COLUMN     "perioperativeNurse1Designation" TEXT,
ADD COLUMN     "perioperativeNurse2" TEXT,
ADD COLUMN     "perioperativeNurse2Designation" TEXT,
ADD COLUMN     "preOpTeachingGiven" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "prescriptionsAttachedToFolder" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "psychologicalStatus" TEXT,
ADD COLUMN     "pulseRate" INTEGER,
ADD COLUMN     "readinessRemarks" TEXT,
ADD COLUMN     "receiptSighted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "receptionRemarks" TEXT,
ADD COLUMN     "requiresAnestheticDrugs" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "requiresBlood" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "requiresCatheterizingBag" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "requiresOtherSpecify" TEXT,
ADD COLUMN     "routineVitalSignsChecked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "specificConcern" TEXT,
ADD COLUMN     "spo2" INTEGER,
ADD COLUMN     "surgeryFeePaidRecorded" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "timeOfPreVisit" TEXT,
ADD COLUMN     "typeOfAnesthesia" TEXT,
ADD COLUMN     "understandingOfProcedure" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "unitsOfBloodAvailable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "useOfAssistiveDevices" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "verificationRemarks" TEXT,
ADD COLUMN     "watchPerOralMaintained" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "weight" DECIMAL(5,2);

-- AlterTable
ALTER TABLE "who_checklists" DROP COLUMN "procedureConfirmed",
DROP COLUMN "recoveryPlan",
ADD COLUMN     "airwayChallenge" BOOLEAN,
ADD COLUMN     "allergyDetails" TEXT,
ADD COLUMN     "anesthetistDate" TIMESTAMP(3),
ADD COLUMN     "anesthetistName" TEXT,
ADD COLUMN     "anesthetistSignature" TEXT,
ADD COLUMN     "antibioticsProphylaxisGiven" TEXT,
ADD COLUMN     "anyEquipmentOrInvestigations" TEXT,
ADD COLUMN     "anyPatientSpecificConcerns" TEXT,
ADD COLUMN     "asaGrade" TEXT,
ADD COLUMN     "aspirationRisk" BOOLEAN,
ADD COLUMN     "bloodAvailableForProcedure" TEXT,
ADD COLUMN     "bloodLossEstimate" TEXT,
ADD COLUMN     "breathingSpontaneously" BOOLEAN,
ADD COLUMN     "checklistCompletedAt" TIMESTAMP(3),
ADD COLUMN     "checklistCompletedBy" TEXT,
ADD COLUMN     "completionOfInstrumentCount" TEXT,
ADD COLUMN     "confirmPatientName" BOOLEAN,
ADD COLUMN     "confirmProcedurePlanned" BOOLEAN,
ADD COLUMN     "criticalOrUnexpectedSteps" TEXT,
ADD COLUMN     "difficultyAirwayRisk" BOOLEAN,
ADD COLUMN     "essentialImagingDisplayed" TEXT,
ADD COLUMN     "hasPatientConfirmedConsent" BOOLEAN,
ADD COLUMN     "hasPatientConfirmedIdentity" BOOLEAN,
ADD COLUMN     "hasPatientConfirmedProcedure" BOOLEAN,
ADD COLUMN     "hasPatientConfirmedSite" BOOLEAN,
ADD COLUMN     "hasSterilityBeenConfirmed" BOOLEAN,
ADD COLUMN     "haveTeamMembersIntroduced" BOOLEAN,
ADD COLUMN     "howMuchBloodlossAnticipated" TEXT,
ADD COLUMN     "icuOrPcuCare" BOOLEAN,
ADD COLUMN     "implantOrGadgetAvailable" TEXT,
ADD COLUMN     "instrumentsSterilityConfirmed" TEXT,
ADD COLUMN     "isAnesthesiaSafetyCheckComplete" BOOLEAN,
ADD COLUMN     "isPulseOximeterOnPatient" BOOLEAN,
ADD COLUMN     "keyConcernsForRecovery" TEXT,
ADD COLUMN     "knownAllergy" BOOLEAN,
ADD COLUMN     "nameOfProcedurePerformed" TEXT,
ADD COLUMN     "nurseVerballyConfirms" BOOLEAN,
ADD COLUMN     "patientFirstName" TEXT,
ADD COLUMN     "patientHospitalNumber" TEXT,
ADD COLUMN     "patientSurname" TEXT,
ADD COLUMN     "patientWard" TEXT,
ADD COLUMN     "perioperativeNurseDate" TIMESTAMP(3),
ADD COLUMN     "perioperativeNurseName" TEXT,
ADD COLUMN     "perioperativeNurseSignature" TEXT,
ADD COLUMN     "postOperativeCareDecisions" TEXT,
ADD COLUMN     "pulseOximeterFunctioning" BOOLEAN,
ADD COLUMN     "riskOfBloodLoss" BOOLEAN,
ADD COLUMN     "specimenLabeling" TEXT,
ADD COLUMN     "surgeonDate" TIMESTAMP(3),
ADD COLUMN     "surgeonName" TEXT,
ADD COLUMN     "surgeonSignature" TEXT,
ADD COLUMN     "surgicalOperation" TEXT,
ADD COLUMN     "teamMembersByNameRole" BOOLEAN,
ADD COLUMN     "transferToRecoveryRoom" BOOLEAN,
ADD COLUMN     "twoIVAccessPlanned" BOOLEAN,
ADD COLUMN     "vitalSignsNormalAndStable" BOOLEAN,
ADD COLUMN     "whatAnticipatedDurationOfSurgery" TEXT,
ADD COLUMN     "whatProcedureSiteFunctionPlanned" TEXT,
ADD COLUMN     "whetherAnyEquipmentProblems" TEXT;

-- CreateTable
CREATE TABLE "surgical_count_checklists" (
    "id" TEXT NOT NULL,
    "surgeryId" TEXT NOT NULL,
    "surgicalOperationType" TEXT,
    "operationDate" TIMESTAMP(3),
    "surgeonName" TEXT,
    "scrubNurseName" TEXT,
    "circulatingNurseName" TEXT,
    "preCountInstruments" INTEGER NOT NULL DEFAULT 0,
    "preCountInstrumentsRecorded" BOOLEAN NOT NULL DEFAULT false,
    "preCountSmallSwabs" INTEGER NOT NULL DEFAULT 0,
    "preCountMediumSwabs" INTEGER NOT NULL DEFAULT 0,
    "preCountLargeSwabs" INTEGER NOT NULL DEFAULT 0,
    "preCountRollSwabs" INTEGER NOT NULL DEFAULT 0,
    "preCountTapeLaparotomy" INTEGER NOT NULL DEFAULT 0,
    "preCountAbdominalPack" INTEGER NOT NULL DEFAULT 0,
    "preCountSwabsRecorded" BOOLEAN NOT NULL DEFAULT false,
    "preCountBlades" INTEGER NOT NULL DEFAULT 0,
    "preCountNeedles" INTEGER NOT NULL DEFAULT 0,
    "preCountSutures" INTEGER NOT NULL DEFAULT 0,
    "preCountTrocars" INTEGER NOT NULL DEFAULT 0,
    "preCountSharpsRecorded" BOOLEAN NOT NULL DEFAULT false,
    "preCountOthers" TEXT,
    "addedInstruments" INTEGER NOT NULL DEFAULT 0,
    "addedSmallSwabs" INTEGER NOT NULL DEFAULT 0,
    "addedMediumSwabs" INTEGER NOT NULL DEFAULT 0,
    "addedLargeSwabs" INTEGER NOT NULL DEFAULT 0,
    "addedRollSwabs" INTEGER NOT NULL DEFAULT 0,
    "addedTapeLaparotomy" INTEGER NOT NULL DEFAULT 0,
    "addedAbdominalPack" INTEGER NOT NULL DEFAULT 0,
    "addedBlades" INTEGER NOT NULL DEFAULT 0,
    "addedNeedles" INTEGER NOT NULL DEFAULT 0,
    "addedSutures" INTEGER NOT NULL DEFAULT 0,
    "addedTrocars" INTEGER NOT NULL DEFAULT 0,
    "addedOthers" TEXT,
    "firstCountInstruments" INTEGER NOT NULL DEFAULT 0,
    "firstCountSmallSwabs" INTEGER NOT NULL DEFAULT 0,
    "firstCountMediumSwabs" INTEGER NOT NULL DEFAULT 0,
    "firstCountLargeSwabs" INTEGER NOT NULL DEFAULT 0,
    "firstCountRollSwabs" INTEGER NOT NULL DEFAULT 0,
    "firstCountTapeLaparotomy" INTEGER NOT NULL DEFAULT 0,
    "firstCountAbdominalPack" INTEGER NOT NULL DEFAULT 0,
    "firstCountBlades" INTEGER NOT NULL DEFAULT 0,
    "firstCountNeedles" INTEGER NOT NULL DEFAULT 0,
    "firstCountSutures" INTEGER NOT NULL DEFAULT 0,
    "firstCountTrocars" INTEGER NOT NULL DEFAULT 0,
    "firstCountOthers" TEXT,
    "firstCountTime" TIMESTAMP(3),
    "firstCountCorrect" BOOLEAN,
    "firstCountDiscrepancy" TEXT,
    "secondCountInstruments" INTEGER NOT NULL DEFAULT 0,
    "secondCountSmallSwabs" INTEGER NOT NULL DEFAULT 0,
    "secondCountMediumSwabs" INTEGER NOT NULL DEFAULT 0,
    "secondCountLargeSwabs" INTEGER NOT NULL DEFAULT 0,
    "secondCountRollSwabs" INTEGER NOT NULL DEFAULT 0,
    "secondCountTapeLaparotomy" INTEGER NOT NULL DEFAULT 0,
    "secondCountAbdominalPack" INTEGER NOT NULL DEFAULT 0,
    "secondCountBlades" INTEGER NOT NULL DEFAULT 0,
    "secondCountNeedles" INTEGER NOT NULL DEFAULT 0,
    "secondCountSutures" INTEGER NOT NULL DEFAULT 0,
    "secondCountTrocars" INTEGER NOT NULL DEFAULT 0,
    "secondCountOthers" TEXT,
    "secondCountTime" TIMESTAMP(3),
    "secondCountCorrect" BOOLEAN,
    "secondCountDiscrepancy" TEXT,
    "allCountsCorrect" BOOLEAN NOT NULL DEFAULT false,
    "finalCountVerifiedBy" TEXT,
    "finalCountWitnessedBy" TEXT,
    "surgeonNotifiedOfCount" BOOLEAN NOT NULL DEFAULT false,
    "discrepancyOccurred" BOOLEAN NOT NULL DEFAULT false,
    "discrepancyType" TEXT,
    "discrepancyDetails" TEXT,
    "discrepancyResolved" BOOLEAN NOT NULL DEFAULT false,
    "discrepancyResolution" TEXT,
    "xRayOrdered" BOOLEAN NOT NULL DEFAULT false,
    "xRayResult" TEXT,
    "incidentReportFiled" BOOLEAN NOT NULL DEFAULT false,
    "countSheetCompleted" BOOLEAN NOT NULL DEFAULT false,
    "signatureScrubNurse" TEXT,
    "signatureCirculatingNurse" TEXT,
    "signatureSurgeon" TEXT,
    "remarks" TEXT,
    "specialNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "completedAt" TIMESTAMP(3),

    CONSTRAINT "surgical_count_checklists_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "surgical_count_events" (
    "id" TEXT NOT NULL,
    "countChecklistId" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "itemType" TEXT NOT NULL,
    "itemDescription" TEXT,
    "quantityAdded" INTEGER,
    "quantityRemoved" INTEGER,
    "recordedBy" TEXT NOT NULL,
    "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "notes" TEXT,

    CONSTRAINT "surgical_count_events_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "surgical_count_checklists_surgeryId_key" ON "surgical_count_checklists"("surgeryId");

-- AddForeignKey
ALTER TABLE "surgical_count_checklists" ADD CONSTRAINT "surgical_count_checklists_surgeryId_fkey" FOREIGN KEY ("surgeryId") REFERENCES "surgeries"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "surgical_count_events" ADD CONSTRAINT "surgical_count_events_countChecklistId_fkey" FOREIGN KEY ("countChecklistId") REFERENCES "surgical_count_checklists"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
