-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PLUMBING_SUPERVISOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'WATER_SUPPLY_SUPERVISOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'EMERGENCY_LAB_SCIENTIST';

-- AlterTable
ALTER TABLE "onboarding_submissions"
  ADD COLUMN IF NOT EXISTS "isContractStaff" BOOLEAN NOT NULL DEFAULT false;
